// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBHEdH7FiLrSG470rvw-eZ88mQo8Pyzic',
    appId: '1:306952175147:android:a5d73e0467f84a1fd4b46e',
    messagingSenderId: '306952175147',
    projectId: 'zayan-training-chat',
    storageBucket: 'zayan-training-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxbNAns3YhrgTGJ90Ed-PPA3sTlmuI9z0',
    appId: '1:306952175147:ios:8032aaa514922743d4b46e',
    messagingSenderId: '306952175147',
    projectId: 'zayan-training-chat',
    storageBucket: 'zayan-training-chat.firebasestorage.app',
    androidClientId: '306952175147-q3t2ae1osbk68j22b9rt6eg36iuandfv.apps.googleusercontent.com',
    iosClientId: '306952175147-td68ee2tfspssrl1f5ini70si5csqh60.apps.googleusercontent.com',
    iosBundleId: 'com.training.chat',
  );

}